//const because we don't want to value of the variable to be overriden
const express = require('express');
const cookieParser = require('cookie-parser');
const app = express();
const port = 8000;
const expressLayouts = require('express-ejs-layouts');
const db = require('./config/mongoose');
//used for session cookie
const session = require('express-session');  //it is a library which encrypts user id and stores in session cookie
const passport = require('passport'); //this is also a library
const passportLocal = require('./config/passport-local-strategy'); //this is also a library
const passportJWT = require('./config/passport-jwt-strategy');
const passportGoogle = require('./config/passport-google-oauth2-strategy');
const MongoStore = require('connect-mongo');

//setting up the middleware that converts scss file to css and then feeds the browser with this file
const sassMiddleware = require('node-sass-middleware');

//setting up flash msgs usage
const flash = require('connect-flash');
const customMware = require('./config/middleware');

//setting to use import and export scss files
app.use(sassMiddleware({
    src: './assets/scss',
    dest: './assets/css',
    debug: true,
    outputStyle: 'extended',
    prefix: '/css'

}));
app.use(express.urlencoded());
app.use(cookieParser());
app.use(express.static('./assets'));

//make the uplaods path available to the browser 
app.use('/uploads', express.static(__dirname + '/uploads'));

app.use(expressLayouts);
//extract styles and scripts from sub pages into the layout
app.set('layout extractStyles', true);
app.set('layout extractScripts', true);


// set up the view engine
app.set('view engine', 'ejs');
app.set('views','./views');

//a middleware that takes in the session cookie(generated by express session) and encrypts it
app.use(session({
    name: 'codeial',
    secret: 'xyz',
    saveUninitialzed: false,
    resave: false,
    cookie: {
        maxAge: (1000*60*100)
    }, 

    // mongo store is used to store the session cookie in the db
    store: new MongoStore({
        // mongooseConnection: db,
        mongoUrl: 'mongodb://localhost/codeial_development',
        autoRemove: 'disabled'
    },

    function(err){
        console.log(err || 'connect-mongodb setup ok');
    }
    )
}));

app.use(passport.initialize());
app.use(passport.session());

app.use(passport.setAuthenticatedUser);

//we need to put this after the session is being used because it uses session cookies
app.use(flash());
app.use(customMware.setFlash);

// use express router
app.use('/',require('./routes/index'));

app.listen(port, function(err){
    if(err){
        console.log(`Error in running the server: ${err}`);
    }

    console.log(`Server is running on port: ${port}`);
});